module.exports = {
    jsxBracketSameLine: false,
    jsxSingleQuote: true,
    proseWrap: "never",
    quoteProps: "as-needed",
    semi: true,
    singleQuote: true,
    tabWidth: 2,
    useTabs: false,
    semi: true,
    trailingComma: "all",
    printWidth: 90,
    endOfLine: "auto",
    bracketSameLine: true,
};